spring:
  redis:
    host: ${REDIS_HOST:111.9.116.136}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:=[;._PL<0okm}
    timeout: ${REDIS_TIMEOUT:5s}
ladybird:
  restful-exception:
    messages:
      token_null_error:
        httpStatus: 400
        message: token不能为空
      credential_timeout_error:
        httpStatus: 400
        message: token超时
      credential_not_found:
        httpStatus: 400
        message: token未找到